// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Client from "@apollo/client";
import * as Apollo$YourProjectName from "../../lib/Apollo.bs.js";
import * as Greeting$YourProjectName from "../Greeting/Greeting.bs.js";

function App(Props) {
  return React.createElement(Client.ApolloProvider, {
              client: Apollo$YourProjectName.instance,
              children: React.createElement(Greeting$YourProjectName.make, {})
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
