// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Greeting(Props) {
  return React.createElement("div", undefined, "Hello Gatsby with Reason");
}

var make = Greeting;

export {
  make ,
  
}
/* react Not a pure module */
